name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Zip Files for Deployment
      run: |
        zip -r app.zip .

    - name: Deploy to Azure
      run: |
        az webapp deploy --resource-group rgcosmosdata --name cosmosinvestApp --src-path app.zip

    - name: Configure Startup Command
      run: |
        az webapp config set --resource-group rgcosmosdata --name cosmosinvestApp --startup-file "uvicorn main:app --host 0.0.0.0 --port 8000"
